### ISSUE TITLE
when using sensu-community/monitoring-checks this chokes on asset version numbers

### ISSUE THREAD

**Issue by ohhfine** [nixwiz/sensu-check-status-metric-mutator#2]
when trying to adopt https://github.com/sensu-community/monitoring-checks rules or templates the version numbers are appended to the asset name, unfortunately they use a (colon) :<version> the mutator does not like this colon and tosses an error

**Comment by nixwiz** [comment]
Can you please provide exact steps for reproducing the error?

**Comment by ohhfine** [comment]
Sorry for the delay, I fumbled around a bit

Everything is centos 8

get a copy of

https://github.com/sensu-community/monitoring-checks/blob/master/system/linux/disk/check-disk-usage.yaml

I think any of them will do it

edit to ensure handler name matches what is on your system (i edit alert to = event-handler)


my mutator
---
type: Mutator
api_version: core/v2
metadata:
  name: sensu-check-status-metric-mutator
  namespace: default
spec:
  command: sensu-check-status-metric-mutator
  runtime_assets:
  - sensu-check-status-metric-mutator

my handler

type: Handler
api_version: core/v2
metadata:
  created_by: skipper
  name: event-storage
  namespace: default
spec:
  command: sensu-influxdb-handler -d events
  env_vars:
  - INFLUXDB_ADDR=http://influx.kk.net:8086
  - INFLUXDB_USER=sensu
  - INFLUXDB_PASS=sensu
  filters: null
  handlers: null
  mutator: sensu-check-status-metric-mutator
  runtime_assets:
  - sensu-influxdb-handler
  secrets: null
  timeout: 0
  type: pipe


install check an associated assets

PS C:\Users\skipper\Downloads> sensuctl create -f .\check-disk-usage.yaml
PS C:\Users\skipper\Downloads>

the error message on the backend

Oct  8 21:50:09 backend sensu-backend[3222275]: {"assets":["sensu-check-status-metric-mutator"],"component":"pipelined","level":"error","msg":"failure in event pipe mutator execution","mutator":"sensu-check-status-metric-mutator","namespace":"default","output":"Usage:\n  sensu-check-status-metric-mutator [flags]\n  sensu-check-status-metric-mutator [command]\n\nAvailable Commands:\n  help        Help about any command\n  version     Print the version number of this plugin\n\nFlags:\n  -h, --help                          help for sensu-check-status-metric-mutator\n  -t, --metric-name-template string   Template for naming the metric point for the check status (default \"{{.Check.Name}}.status\")\n\nUse \"sensu-check-status-metric-mutator [command] --help\" for more information about a command.\n\nError executing sensu-check-status-metric-mutator: check is invalid: asset's name must be lowercase and may only contain forward slashes, underscores, dashes and numbers\n","status":1,"time":"2020-10-08T21:50:09-04:00"}



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nixwiz** [comment]
Thanks for bringing this to my attention.  I've updated and created a new release that is available on Bonsai.

**Comment by ohhfine** [comment]
excellent, well done and thank you I will get it in tonight and kick the tires a bit

Andrew

________________________________
